image: debian/stable
packages: 
- git
- lua-busted
sources :
- https://git.sr.ht/~gpcf/advtrains

tasks:

- run_unit_tests : |
    cd advtrains/advtrains
    busted
    cd ../advtrains_interlocking
    busted
    cd ../serialize_lib
    busted
