image: debian/stable
packages: 
- git
- curl
- minetest-server
- unzip
- wget
- lua5.1
- luarocks
sources :
- https://git.sr.ht/~gpcf/advtrains

tasks:

- download_mt_server: |
    mkdir bin
    wget https://lifomaps.de/advtrains-test/builtin.tar.gz
    tar xf builtin.tar.gz
    curl https://lifomaps.de/advtrains-test/minetestserver -o ~/bin/minetestserver
    chmod +x ~/bin/minetestserver
- install_mt_game : |
    curl -L https://github.com/minetest/minetest_game/archive/master.zip -o master.zip
    mkdir -p .minetest/games/
    cd .minetest/games
    unzip ../../master.zip
    mv minetest_game-master minetest_game
- install_test_world: |
    mkdir -p .minetest/worlds/
    curl https://lifomaps.de/advtrains-test/testworld.tar.gz -o ~/testworld.tar.gz
    cd .minetest/worlds/
    tar xf ../../testworld.tar.gz
- install_mineunit : |
    for i in {busted,luacov}; do
        luarocks install --local --lua-version 5.1 $i >/dev/null
    done
    luarocks install --local --lua-version 5.1 --server=https://luarocks.org/dev mineunit
- run_unit_tests : |
    cd advtrains/serialize_lib
    ~/.luarocks/bin/busted
    for i in {advtrains,advtrains_interlocking}; do
        cd ../$i
        ~/.luarocks/bin/mineunit -c
        ~/.luarocks/bin/mineunit -r
        sed -n '/^File/,$p' luacov.report.out
    done
- activate_test_env: |
    cd advtrains
    git merge --no-commit origin/luaatcdebug
- install_advtrains : |
    mkdir .minetest/mods
    cp -r advtrains .minetest/mods
    cd .minetest/mods
    git clone https://git.bananach.space/basic_trains.git/
- run_test_world: | 
    echo "bind_address = 127.0.0.1" > minetest.conf
    ~/bin/minetestserver --port 31111 --gameid minetest_game --config ~/minetest.conf --world ~/.minetest/worlds/advtrains_testworld
